apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "uber-app.fullname" . }}-ui
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "uber-app.fullname" . }}-ui
                port:
                  number: 80