apiVersion: v1
kind: Service
metadata:
  name: uber-ui
spec:
  selector:
    app: uber-ui
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}