replicaCount: 2
image:
  repository: infrastructureacrzXyRr0Uzr2MS52e6.azurecr.io/uberapp
  tag: eaf26
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  annotations:
    kubernetes_io_ingress_class: azure/application-gateway
  path: /
  pathType: Prefix
  serviceName: uber-ui
  servicePort: 80

namespace:
  Name: production
