name: Build and push Docker image to ACR
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.author.email, 'github-actions[bot]@users.noreply.github.com')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.LOGIN_SERVER }}
          username: ${{ secrets.CLIENT_ID }}
          password: ${{ secrets.CLIENT_SECRET }}

      - name: Build image
        run: docker build -t uberapp .

      - name: Get commit SHA
        run: |
          COMMIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-5)
          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV

      - name: Tag image
        run: docker tag uberapp ${{ vars.LOGIN_SERVER }}/uberapp:${{ env.COMMIT_SHA }}
      
      - name: Push image
        run: docker push ${{ vars.LOGIN_SERVER }}/uberapp:${{ env.COMMIT_SHA }}

      - name: modify image tag for HELM
        working-directory: ./helm
        run: |
          # Set the new image tag
          new_image_tag=${{ env.COMMIT_SHA }}
          
          # Create a temporary file
          temp_file=$(mktemp)
          
          # Read the input YAML file and replace the image tag, preserving spaces
          awk -v new_tag="$new_image_tag" '
              /^image:/,/^  pullPolicy:/ {
                  if ($1 == "tag:") {
                      print "  tag:", new_tag
                      next
                  }
              }
              { print }
          ' Values.yaml > "$temp_file"
          
          # Replace the original YAML file with the updated one
          mv "$temp_file" Values.yaml
          cat Values.yaml
          
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Modify Helm Chart with new build version"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: ${{ github.ref }}


        
