name: Modify Tag Value
on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: modify image tag for HELM
        run: |
          yaml=$(cat helm/Values.yaml)
          echo $yaml